language: python
sudo: false
python:
  - 3.6
  - 3.6-dev
  - 3.7-dev
  - nightly
before_script:
  - pip install python-coveralls
script: pytest --pep8 coveralls --cov coveralls -cov-report term-missing
after_success: coveralls