language: python
sudo: false
os:
  - linux
python:
  - 3.6
  - 3.6-dev
  - 3.7-dev
  - nightly
before_install:
  - pip install pytest pytest-cov
  - pip install python-coveralls
  - pip install coveralls
script: pytest
after_success:
    - coveralls
