language: python
sudo: false
os:
  - linux
  - osx
python:
  - 3.6
  - 3.6-dev
  - 3.7-dev
  - nightly
before_install:
  - pip install pytest pytest-cov
  - pip install coveralls
script: pytest
after_success:
    - if [[ $ENV == python=3.6* ]]; then
          coveralls;
      fi
